services:
  frontend:
    build: ./frontend
    depends_on:
      - db
      - backend
    ports:
      - '5173:5173'
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - '8000:8000'

  db:
    image: postgres:18
    environment:
      POSTGRES_DB: monostich
      POSTGRES_USER: monostich_admin
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
